names:
  background-color: bgc
  background: bg
  background-attachment: ba
  background-clip: bc
  background-color: bgc
  background-image: bgi
  background-origin: bgo
  background-position: bgp
  background-repeat: bgr
  background-size: bgs
  border: bo
  border-color: boc
  border-radius: bor
  border-width: bow
  border-style: bos
  bottom: b
  box-shadow: bs
  clear: clr
  clip: cl
  color: c
  column-count: colc
  column-fill: colf
  column-gap: colg
  column-rule: colr
  column-rule-color: colrc
  column-rule-style: colrs
  column-rule-width: colrw
  column-span: colspan
  column-width: colw
  columns: col
  content: content
  cursor: crsr
  direction: dir
  display: d
  filter: fltr
  flex-basis: flb
  flex-direction: fld
  flex-flow: flf
  flex-grow: flg
  flex-shrink: fls
  flex-wrap: flw
  float: fl
  font: f
  font-family: ff
  font-size: fs
  font-style: TODO
  font-variant: TODO
  font-weight: fw
  height: h
  justify-content: jc
  left: l
  letter-spacing: ls
  line-break: lb
  line-height: lh
  list-style-image: lsi
  list-style-position: lsp
  list-style-type: lst
  margin: m
  margin-bottom: mb
  margin-left: ml
  margin-right: mr
  margin-top: mt
  max-height: mxh
  max-width: mxw
  min-height: mnh
  min-width: mnw
  opacity: o
  order: or
  outline: ol
  outline-color: olc
  outline-offset: olo
  outline-style: ols
  outline-width: olw
  overflow: of
  overflow-wrap: ovw
  overflow-x: ovx
  overflow-y: ovy
  padding: p
  padding-bottom: pb
  padding-left: pl
  padding-right: pr
  padding-top: pt
  perspective: psp
  perspective-origin: pspo
  pointer-events: pe
  position: pos
  right: r
  rotate(): rot
  rotate3d(): rot3d
  rotateX(): rotx
  rotateY(): roty
  rotateZ(): rotz
  scale(): scl
  scale3d(): scl3d
  scaleX(): sclx
  scaleY(): scly
  scaleZ(): sclz
  skew(): skw
  skewX(): skwx
  skewY(): skwy
  text-align: ta
  text-decoration: td
  text-decoration-color: tdc
  text-decoration-line: tdl
  text-decoration-style: tds
  text-emphasis: te
  text-emphasis-color: tec
  text-emphasis-position: tep
  text-emphasis-style: tes
  text-indent: ti
  text-orientation: tor
  text-overflow: to
  text-shadow: ts
  text-transform: tt
  text-underline-position: tup
  top: t
  transform: tfm
  transform-origin: tfmo
  transform-style: tfms
  transition: trs
  transition-delay: trsdl
  transition-duration: trsdu
  transition-property: trsp
  transition-timing-function: trst
  translate(): tsl
  translate3d(): tsl3d
  translateX(): tslx
  translateY(): tsly
  translateZ(): tslz
  vertical-align: va
  visibility: v
  vmax: vmx
  vmin: vmn
  white-space: ws
  width: w
  will-change: wc
  word-break: wb
  word-spacing: ws
  word-wrap: ww
  writing-mode: wm
  z-index: z

values:
  block: b
  inline-block: ib

expansions:
  top: t
  right: r
  bottom: b
  left: l
